<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>topic_command_controller</name>
  <version>0.0.1</version>
  <description>ros2_control bridge: command/joint_command topic to loaned command interfaces (sim-only)</description>
  <maintainer email="zhepeng19@gmail.com">zhepeng</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>pluginlib</depend>
  <depend>hardware_interface</depend>
  <depend>controller_interface</depend>
  <depend>controller_manager</depend>
  <depend>ddt_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
